### PR TITLE
Transferred from personal repo to organization, corrected  references…

### PR DESCRIPTION
**Pull request by edstros**
Transferred from personal repo to organization; corrected paths to Firebase.

### CODE REVIEW

**Comment by edstros** [comment]
Change Firebase references to connect to nashvillebarcamp.firebaseio.com.

**Comment by sunderhaus** [comment]
Edwin, it looks like whatever editor your using has rewritten every file in the project with whitespace corrections. Can you update this PR without those whitespace changes?

**Comment by mccool** [comment]
You could add a .editorconfig file to the root of the project and specify
```
root = true

[*]
indent_style = tab
indent_size = 4
```

* indent_style: set to tab or space to use hard tabs or soft tabs respectively.

* indent_size: a whole number defining the number of columns used for each indentation level and the width of soft tabs (when supported). When set to tab, the value of tab_width (if specified) will be used.

**Comment by sunderhaus** [comment]
Whoa, awesome tip, Blake. That's not something I've ever used. Adding one of those would still require a one time correction to whitespace made by somebody, yes?

**Comment by mccool** [comment]
most likey, but it would provide consistency for the future.

**Comment by sunderhaus** [comment]
I do like the consistency idea. It looks like the .editorconfig would require a plugin for most editors.

* Brackets: https://github.com/kidwm/brackets-editorconfig/
* Atom: https://github.com/sindresorhus/atom-editorconfig

**Comment by sunderhaus** [comment]
Closing this since I added the changes without the whitespace to the 'dev' branch. Please re-branch to continue contributing!

**Pull request closed without merging**
